AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an S3 Bucket"
Resources:
    MyS3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            BucketName: mergeddata09
    
    GlueJobImport:
        Type: AWS::Glue::Job
        DependsOn: MyS3Bucket
        Properties:
            Name: data-import1
            Description: Ingests data from s3 and writes it as a parquet file to the data lake
            ExecutionClass: FLEX
            GlueVersion: 4.0
            MaxRetries: 0
            NumberOfWorkers: 6
            Role: arn:aws:iam::467280971091:role/LabRole
            Timeout: 30
            WorkerType: G.1X
            Command:
                Name: glueetl
                ScriptLocation: s3://github-scrpits/Datawarehouse_Script.py

    LambdaTrigger:
        Type: AWS::Lambda::Function
        Properties:
            Code:
              ZipFile: |
                  import boto3
                  def lambda_handler(event, context):
                    glue_client = boto3.client('glue')
                    job_name = 'data-import1'
                    response = glue.start_job_run(JobName=job_name)
            FunctionName: Trigger
            Handler: index.lambda_handler
            Role: arn:aws:iam::467280971091:role/LabRole
            Runtime: python3.11
            Timeout: 10

    GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: database2   
    
    GlueCrawler:
        Type: AWS::Glue::Crawler
        Properties:
            Name: CrawlingData1
            DatabaseName: database2
            Targets:
                S3Targets:
                    - Path: s3://mergeddata09/datawarehouse/
            Role: arn:aws:iam::467280971091:role/LabRole