AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an S3 Bucket"

Resources:

    MyS3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: mergeddatar18


    GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: database66  
                   

    WorkflowJob:
        Type: AWS::Glue::Workflow
        Properties:
            Description: Create workflow
            MaxConcurrentRuns: 1
            Name: jobworkflow1        
    
    GlueJobImport:
        Type: AWS::Glue::Job
        DependsOn: MyS3Bucket
        Properties:
            Name: data-importsep39
            Description: Ingests data from s3 and writes it as a parquet file to the data lake
            ExecutionClass: FLEX
            GlueVersion: 4.0
            MaxRetries: 0
            NumberOfWorkers: 6
            Role: arn:aws:iam::077117346067:role/LabRole
            Timeout: 40
            WorkerType: G.1X
            Command:
                Name: glueetl
                ScriptLocation: s3://shraddha-newbucket1/Datawarehouse_Script.py

    
    GlueCrawler:
        Type: AWS::Glue::Crawler
        Properties:
            Name: CrawlingData64
            DatabaseName:  database64
            Targets:
                S3Targets:
                    - Path: s3://mergeddatar18/datawarehouse/
            Role: arn:aws:iam::077117346067:role/LabRole
    
  
    WorkflowStartTrigger:
          Type: AWS::Glue::Trigger
          Properties:
              Name: StartTrigger
              Type: ON_DEMAND
              Description: Trigger for starting the workflow
              Actions:
                - JobName: !Ref GlueJobImport
              WorkflowName:  !Ref WorkflowJob

    CrawlerJobTrigger:
        Type: AWS::Glue::Trigger
        Properties:
            Name: jobsuccesfultrigger1
            Type: CONDITIONAL
            StartOnCreation: TRUE
            Description: Trigger to start the crawler
            Actions:
              - CrawlerName :  CrawlingData64
            Predicate: 
              Conditions:
                - LogicalOperator: EQUALS
                  JobName: !Ref GlueJobImport
                  State: SUCCEEDED
            WorkflowName: !Ref WorkflowJob  
            
            
    MyAthenaWorkGroup:
        Type: AWS::Athena::WorkGroup
        Properties:
            Name: MyWorkGroup
            Description: workgroup for Athena
            State: ENABLED
            WorkGroupConfiguration:
                BytesScannedCutoffPerQuery: 200000000
                EnforceWorkGroupConfiguration: false
                PublishCloudWatchMetricsEnabled: true
                RequesterPaysEnabled: true
                ResultConfiguration:
                    OutputLocation: s3://bigdatagithubproject/    


    # StateMachine:
    #     Type: AWS::StepFunctions::StateMachine
    #     Properties:
    #         Role : arn:aws:iam::467280971091:role/LabRole
    #         StateMachineName : jamm
    #         DefinitionString:
    #             Fn::Sub: |
    #                {
    #                 "Comment": "A state machine to run Glue Job and trigger Glue Crawler",
    #                 "StartAt": "RunGlueJob",
    #                 "States": {
    #                 "RunGlueJob": {
    #                     "Type": "Task",
    #                     "Resource": "arn:aws:states:::glue:startJobRun.sync",
    #                     "Parameters": {
    #                           "JobName": "data-importsep38"
    #                     },
    #                     "Next": "CheckGlueJobStatus"
    #                 },
    #                 "CheckGlueJobStatus": {
    #                     "Type": "Choice",
    #                     "Choices": [
    #                         {
    #                           "Variable": "$.JobRun.JobRunState",
    #                           "StringEquals": "SUCCEEDED",
    #                           "Next": "StartCrawler"
    #                         }
    #                     ],
    #                     "Default": "WaitForJobCompletion"
    #                 },
    #                 "WaitForJobCompletion": {
    #                     "Type": "Wait",
    #                     "Seconds": 60,
    #                     "Next": "RunGlueJob"
    #                 },
    #                     "StartCrawler": {
    #                         "Type": "Task",
    #                         "Resource": "arn:aws:states:::glue:startCrawlerSync",
    #                         "Parameters": {
    #                         "CrawlerName": "CrawlingData64"
    #                     },
    #                     "End": true
    #                  }
    #                 }
    #                }
        
   
       