AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an S3 Bucket"

Parameters:
    # ExecutionClass:
    #     Type: String
    #     Description: "Execution Class"
      
    
    # MaxRetries:
    #     Type: Number
    #     Description: "Number of Max. Retries of Glue Job"
      

    NumberOfWorkers:
        Type: Number
        Description: "Number of Glue Job workers"
 

    LabRole:
        Type: String
        Description: "LabRole"
        Default: arn:aws:iam::467280971091:role/LabRole

    Timeout:
        Type: Number
        Description: "Timeout for Glue Job"
        

    WorkerType:
        Type: String
        Description: "Type of Glue job Worker"
       
        

Resources:

    MyS3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: datalake-rawzone-grp41

    MyS3Bucket12:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: output-grp41  

    GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: gitdatabase1
                   

    WorkflowJob:
        Type: AWS::Glue::Workflow
        Properties:
            Description: Create workflow
            MaxConcurrentRuns: 1
            Name: jobworkflow11        
    
    GlueJobImport:
        Type: AWS::Glue::Job
        DependsOn: MyS3Bucket
        Properties:
            Name: data-ingestion1
            Description: Ingests data from s3 and writes it as a parquet file to the data lake
            ExecutionClass: FLEX
            GlueVersion: 4.0
            MaxRetries: 0
            NumberOfWorkers: !Ref NumberOfWorkers
            Role: !Ref LabRole
            Timeout: !Ref Timeout
            WorkerType: !Ref WorkerType
            Command:
                Name: glueetl
                ScriptLocation: s3://projectgitlab/Datawarehouse_Script.py

    
    GlueCrawler:
        Type: AWS::Glue::Crawler
        Properties:
            Name: CrawlingData1
            DatabaseName:  gitdatabase1
            Targets:
                S3Targets:
                    - Path: s3://datalake-rawzone-grp4/structure/
            Role: !Ref LabRole
    
  
    WorkflowStartTrigger:
          Type: AWS::Glue::Trigger
          Properties:
              Name: StartTrigger1
              Type: ON_DEMAND
              Description: Trigger for starting the workflow
              Actions:
                - JobName: !Ref GlueJobImport
              WorkflowName:  !Ref WorkflowJob

    CrawlerJobTrigger:
        Type: AWS::Glue::Trigger
        Properties:
            Name: jobsuccesfultrigger12
            Type: CONDITIONAL
            StartOnCreation: TRUE
            Description: Trigger to start the crawler
            Actions:
              - CrawlerName :  CrawlingData1
            Predicate: 
              Conditions:
                - LogicalOperator: EQUALS
                  JobName: !Ref GlueJobImport
                  State: SUCCEEDED
            WorkflowName: !Ref WorkflowJob  
            
            
    MyAthenaWorkGroup:
        Type: AWS::Athena::WorkGroup
        Properties:
            Name: MyGroup1
            Description: workgroup for Athena
            State: ENABLED
            WorkGroupConfiguration:
                BytesScannedCutoffPerQuery: 200000000
                EnforceWorkGroupConfiguration: false
                PublishCloudWatchMetricsEnabled: true
                RequesterPaysEnabled: true
                ResultConfiguration:
                    OutputLocation: s3://output-grp41/    


    
   
       