name: combine

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #   - name: Upload to S3
    #     run: |
    #       aws s3 cp .github/workflows/PythonScript.py s3://github1trial1/data/
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  #access id error
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       AWS_DEFAULT_REGION: us-east-1
    #       AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name trail1 \
            --template-file .github/workflows/cft.yml \   
            --capabilities CAPABILITY_NAMED_IAM 
        #name of IAM is not required Only Defined variables has to be used 3 types   
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}




