name: create crawler1

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      NumberOfWorkers:
        description: "Enter the Number of Workers Required"
        default: 3
        type: "integer"
        Required : false

jobs:
  prepare and test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master


  AWS Cloudformation Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name rashedingest17 \
            --template-file .github/workflows/cft1.yml \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


          


































































